#!/bin/bash
# A script which parses through sitemap and dumps all urls in the sitemap
# The urls in a file called urls.txt in the tmp/sites directory 

# Read the SiteMap dump and get all the URLs out. 
# Process it further incase there are other sitemaps
function waitForJobs() {
  local pid
  local status=0
  for pid in "$@"; do
    wait "$pid" || status=1
  done
  return "$status"
}

function readAndStripUrl() {
  local pids=()
  urls=$(
    cat $1 \
      | sed 's#<loc>#\r\n<loc>#g' \
      | grep loc | grep http \
      | sed 's#.*loc>\(.*\)<\(.*\)loc>.*#\1#' \
      | tr " " "\n"
  ) 
  for i in ${urls[@]}; do
    processUrl "$i" &
    pids+=("$!")
  done
  waitForJobs "${pids[@]}"
}


# Process the Url(s) and create the respective directory and files
function processUrl() {
   dir="$(echo $i | sed 's#www.##g' | sed 's#^https://\([^/]*\).*#\1#')";
   
   if [[ "$i" != *".xml"* ]]; then
      echo "$i" >> "$dir/urls.txt"
   else
     file="$(echo $i | sed 's#.*/\(.*\)#\1#')";
     mkdir -p "$dir" || return 1
     echo "Fetching URLs from site-map: $i"
     curl -fsSL "$i" >> "$dir/$file" || return 1
     readAndStripUrl "$dir/$file"
   fi
}


if ! cd /tmp/ || ! mkdir -p site || ! cd site; then
  echo "Unable to prepare /tmp/site" >&2
  exit 1
fi

if [ "$#" -eq 0 ]; then
  echo "Pass a Site Map URL" >&2
  exit 1
else
  pids=()
  for i in "$@"; do
    processUrl "$i" &
    pids+=("$!")
  done
  if ! waitForJobs "${pids[@]}"; then
    echo "Site scrape failed" >&2
    exit 1
  fi
  echo "Site Scraped!!"
fi

